/* AWARDS BEGIN */
insert into tb_awards (award_id, award_year, category, author, title, text, text_html) values (1, 2019, 'PHYSICS', 'James Peebles', 'por descobertas teóricas em cosmologia física', '', '');
insert into tb_awards (award_id, award_year, category, author, title, text, text_html) values (2, 2019, 'PHYSICS', 'Michel Mayor e Didier Queloz', 'pela descoberta de um exoplaneta orbitando uma estrela do tipo solar', '', '');
insert into tb_awards (award_id, award_year, category, author, title, text, text_html) values (3, 2019, 'CHEMISTRY', 'John B. Goodenough, M. Stanley Whittingham e Akira Yoshino', 'pelo desenvolvimento de baterias de íons de lítio', '', '');
insert into tb_awards (award_id, award_year, category, author, title, text, text_html) values (4, 2019, 'PHYSIOLOGY_MEDICINE', 'William G. Kaelin Jr, Sir Peter J. Ratcliffe e Gregg L. Semenza', 'por suas descobertas de como as células sentem e se adaptam à disponibilidade de oxigênio', '', '');
insert into tb_awards (award_id, award_year, category, author, title, text, text_html) values (5, 2019, 'LITERATURE', 'Peter Handke', 'por um trabalho influente que, com engenhosidade linguística, explorou a periferia e a especificidade da experiência humana', '', '');
insert into tb_awards (award_id, award_year, category, author, title, text, text_html) values (6, 2019, 'PEACE', 'Abiy Ahmed Ali', 'pelos seus esforços para alcançar a paz e a cooperação internacional e, em particular, pela sua iniciativa decisiva para resolver o conflito fronteiriço com a vizinha Eritreia', '', '');
insert into tb_awards (award_id, award_year, category, author, title, text, text_html) values (7, 2019, 'ECONOMIC_SCIENCES', 'Abhijit Banerjee, Esther Duflo e Michael Kremer', 'por sua abordagem experimental para aliviar a pobreza global', '', '');
/* AWARDS END */

/* DIDYOUKNOW BEGIN */
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (1, 'Quando os cientistas não existiam','antes do século XVII, a ciência e os cientistas não eram verdadeiramente reconhecidos. Inicialmente, pessoas como o gênio Isaac Newton do século XVII eram chamadas filósofos naturais, porque não havia conceito da palavra "cientista" na época.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (2, 'O J ausente','A única letra que não aparece na tabela periódica é J.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (3, 'Cubos em expansão','um cubo de gelo ocupa cerca de 9% a mais do que a água usada para produzi-lo.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (4, 'A temperatura do raio','um raio pode atingir uma temperatura de 30.000 C ou 54.000 F. Cerca de 400 pessoas são atingidas por um raio a cada ano.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (5, 'Marte enferrujado','Em Marte, o óxido de ferro forma um pó de ferrugem que flutua na atmosfera e cria um revestimento em grande parte da paisagem.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (6, 'Quando a água quente congela','A água quente pode congelar mais rápido que a água fria. No entanto, isso nem sempre acontece, nem a ciência explicou exatamente por que isso pode acontecer.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (7, 'Insetos dormem','os insetos claramente descansam às vezes e são despertados apenas por fortes estímulos - o calor do dia, a escuridão da noite ou talvez um ataque repentino de um predador. Esse estado de repouso profundo é chamado torpor e é o comportamento mais próximo do sono verdadeiro que os insetos exibem.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (8, 'Todo mundo é seu parente','todo ser humano tem 99% de seu DNA em comum. Pai e filho compartilham 99,5% do mesmo DNA e você tem 98% do seu DNA em comum com um chimpanzé.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (9, 'O cérebro roubado de Einstein','Após a morte de Albert Einstein em 1955, o patologista Thomas Harvey, no Hospital de Princeton, conduziu uma autópsia na qual ele removeu o cérebro de Albert Einstein. Em vez de colocar o cérebro de volta no corpo, Harvey decidiu mantê-lo para estudo. Harvey não tinha permissão para manter o cérebro de Einstein, mas dias depois ele convenceu o filho de Einstein de que isso ajudaria a ciência.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (10, 'Orelhas no estômago','Em cada lado do primeiro segmento abdominal de um gafanhoto, escondido embaixo das asas, você encontrará membranas que vibram em resposta às ondas sonoras. Esse tímpano simples, chamado tímpana, permite ao gafanhoto ouvir as canções de acasalamento dos membros de sua espécie.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (11, 'Isso é nítido', 'seis elementos representam 99% da massa do corpo humano oxigênio, carbono, hidrogênio, nitrogênio, cálcio e fósforo. O corpo humano contém carbono suficiente para 9.000 lápis.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (12, 'Portando daltonismo','As mulheres geralmente são portadoras da mutação genética do daltonismo, que é transmitida através do cromossomo X. São principalmente os homens que herdam a daltonismo, afetando cerca de 1 em cada 20 homens para 1 em cada 200 mulheres.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (13, 'A importância da boa higiene','os cupins passam muito tempo se arrumando. Sua boa higiene é importante para sua sobrevivência, pois mantém os parasitas e as bactérias nocivas sob controle dentro da colônia.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (14, 'A utilidade da saliva','os seres humanos não podem provar comida sem saliva. Os quimiorreceptores nas papilas gustativas da sua língua requerem um meio líquido para que os sabores se liguem às moléculas receptoras.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (15, 'Somos principalmente bactérias','os cientistas estimaram que cerca de 95% de todas as células do corpo são bactérias. A grande maioria desses micróbios pode ser encontrada no trato digestivo.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (16, 'Mercúrio não está enlouquecendo','embora o planeta Mercúrio possa se parecer com a nossa própria lua de muitas maneiras, ele não tem lua própria.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (17, 'Saindo com um flash','Nos próximos 5 bilhões de anos, o sol ficará cada vez mais brilhante à medida que o hidrogênio em seu núcleo se acostumar, criando pressão interna aumentada e, portanto, conversão de combustível em hélio. Em 1,1 bilhão de anos, o planeta poderia começar a se parecer com Vênus. Eventualmente, o Sol ficará sem combustível de hidrogênio e entrará em colapso.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (18, 'Protetor solar para a língua','as línguas das girafas são azul escuro (ou arroxeado ou cinza escuro). O comprimento de suas línguas lhes permite procurar folhas mais altas e suculentas em suas acácias favoritas, e a melanina em suas línguas pode protegê-las dos raios UV.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (19, 'Estegossauro com cérebro de limão','o estegossauro era equipado com um cérebro pequeno, do tamanho de um limão, comparável ao de um golden retriever moderno. Os cérebros dos dinossauros carnívoros eram maiores que os dos comedores de folhas, pois precisavam de mais massa cinzenta para caçar presas móveis.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (20, 'Cefalópode de três corações','dois corações são usados para bombear sangue para cada pulmão do polvo, e o terceiro bombeia sangue por todo o corpo.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (21, 'Tartarugas centenárias','As tartarugas de Galápagos podem ter mais de 100 anos de idade. Eles também são a maior de todas as tartarugas vivas, medindo até 1,2 m de comprimento e pesando mais de 158,8 kg.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (22, 'Fumar mata','A nicotina pode ser letal para crianças em doses tão pequenas quanto 10 miligramas. Mais comumente conhecido como ingrediente viciante em produtos de tabaco, a nicotina é frequentemente considerada erroneamente como um produto químico inofensivo.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (23, 'Baleias assassinas e/ou golfinhos','a baleia assassina, ou orca, é considerada um golfinho. O nome dos animais foi originalmente traduzido como "matador de baleias", mas foi mudado. Mas um golfinho é uma das 38 espécies de baleias com dentes, então talvez o nome não esteja tão distante assim.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (24, 'Voo com asas de morcego','os morcegos são o único grupo de mamíferos do mundo que tem asas. Embora alguns outros grupos de mamíferos possam planar usando membranas da pele, apenas os morcegos são capazes de voar de verdade.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (25, 'Água mortal','é possível morrer por beber muita água. A intoxicação por água e a hiponatremia ocorrem quando uma pessoa desidratada bebe muita água sem os eletrólitos que a acompanham.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (26, 'Falta flutuante','Qual é a maneira de saber se um ovo mais velho está fresco? Coloque um ovo em um recipiente de água. Se o ovo ficar inclinado ou ficar em uma das extremidades, o ovo fica mais velho, mas ainda é comestível. Se o ovo flutuar, se cheirar ou parecer ruim quando rachado, ele deve ser descartado. Os ovos acumulam ar dentro de suas células aéreas à medida que envelhecem, levando ao aumento da flutuação.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (27, 'Formigas Pesadas','As formigas são capazes de transportar objetos 50 vezes o seu próprio peso corporal. Em relação ao seu tamanho, os músculos das formigas são mais espessos do que os de animais maiores ou até humanos. Essa proporção permite que eles produzam mais força e transportem objetos maiores.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (28, 'Óculos de água embutidos','os olhos dos pinguins funcionam melhor debaixo da água do que no ar. Esse privilégio dá a eles uma visão superior para identificar presas enquanto caçam, mesmo em águas nubladas ou escuras.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (29, 'Bananas radiantes','As bananas contêm altos níveis de potássio e, portanto, são levemente radioativas. Não é algo com que você precise se preocupar, porque 0,01% do potássio já existente no seu corpo é do mesmo tipo radioativo (K-40). O potássio é essencial para uma nutrição adequada.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (30, 'A artrite afeta qualquer pessoa','O equívoco mais popular sobre a artrite é que é uma doença de pessoa idosa. Na realidade, a artrite afeta pessoas de todas as idades, incluindo cerca de 300.000 crianças. No entanto, as crianças tendem a ter um prognóstico mais favorável do que os adultos.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (31, 'O ácido que derrete tudo','mesmo que seja altamente corrosivo e possa dissolver o vidro, o ácido fluorídrico não é considerado um ácido forte porque não se dissocia completamente na água. O armazenamento geralmente é em recipientes de plástico, porque é muito reativo com metal, cerâmica e vidro.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (32, 'Adicione flores à sua salada','pétalas de rosa são comestíveis. As rosas pertencem à mesma família das maçãs, de modo que a semelhança de seus frutos não é pura coincidência.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (33, 'Mas não é por isso que o céu é azul','o gás oxigênio é incolor, inodoro e insípido. No entanto, as formas líquida e sólida são de uma cor azul pálida.','');
insert into tb_didyouknow (didyouknow_id, title, text, text_html) values (34, 'Os 95% misteriosos','os humanos podem ver apenas 5% da matéria no universo. O resto é composto de matéria invisível (chamada matéria escura) e uma forma misteriosa de energia conhecida como energia escura.','');
/* DIDYOUKNOW END */
